# Generated by Django 5.2.1 on 2025-10-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_rename_detalle_pedido_detallepedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='hub.pedidos'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='hub.usuarios'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(default='usuario', max_length=50),
        ),
    ]
