# Generated by Django 5.2.1 on 2025-10-02 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_productos_imagen_alter_detallepedido_id_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
