# Generated by Django 5.2.1 on 2025-10-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
